apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: polar-service
  labels:
    app: catalog-service
spec:
  type: ClusterIP
  selector:
    app: catalog-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: polar-service
  labels:
    app: config-service
spec:
  type: ClusterIP
  selector:
    app: config-service
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: polar-postgres
  namespace: polar-service
  labels:
    db: polar-postgres
spec:
  type: ClusterIP
  selector:
    db: polar-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catalog-service-ingress
  namespace: polar-service
  annotations:
    kubernetes.io/ingress.class: "traefik"  # Traefik Ingress Controller 사용
spec:
  rules:
    - host: catalog.service.com   # 접속할 도메인
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: catalog-service   # Service 이름
                port:
                  number: 80         # 서비스가 노출하는 포트

